FROM node:24-alpine

WORKDIR /app

# Salin file package dulu untuk install dependensi
COPY package*.json ./

# Install dependensi (menggunakan --frozen-lockfile jika ada, atau biasa)
RUN npm install

# Salin semua file lainnya
COPY . .

# EXPOSE port 3000
EXPOSE 3000

# Gunakan perintah ini agar container tidak langsung mati
CMD ["npm", "run", "dev"]